#!/usr/bin/env bash
# This script displays user information in the specific format
while IFS=: read -r username _ uid gid _ _ homedir; do
  # Exclude the shell field output (print "." as per expected format)
  echo "The user $username is part of the $gid gang, lives in $homedir and rides ."
  echo "User ID's place is protected by the passcode $uid, more info about the user here: $username"
  echo
done < /etc/passwd
