#!/usr/bin/env bash
# This script displays information about users in the /etc/passwd file in a specific format
while IFS=: read -r username _ uid gid _ _ homedir shell; do
  echo "The user $username is part of the $gid gang, lives in $homedir and rides $shell."
  echo "User ID's place is protected by the passcode $uid, more info about the user here: $uid INFO"
  echo
done < /etc/passwd
