#!/bin/bash
# This script groups visitors by IP and HTTP status code, and displays the data in sorted order
awk '{print $1, $9}' /path/to/apache-access.log | 
  sort | 
  uniq -c | 
  sort -nr | 
  awk '{print $1, $2, $3}'
