#!/usr/bin/env bash
# Manages "my process"


PID_FILE="/var/run/my_process.pid"
PROCESS_SCRIPT="/alu-shell/processes_and_signals/manage_my_process"  

case "$1" in
    start)
        if [ -f "$PID_FILE" ]; then
            echo "manage_my_process is already running"
            exit 1
        fi
        nohup bash "$PROCESS_SCRIPT" &> /dev/null &
        echo $! > "$PID_FILE"
        echo "manage_my_process started"
        ;;

    stop)
        if [ -f "$PID_FILE" ]; then
            kill "$(cat "$PID_FILE")" && rm -f "$PID_FILE"
            echo "manage_my_process stopped"
        else
            echo "manage_my_process is not running"
            exit 1
        fi
        ;;

    restart)
        $0 stop > /dev/null 2>&1
        $0 start > /dev/null 2>&1
        echo "manage_my_process restarted"
        ;;

    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac
